language: node_js
node_js:
  - 0.10
  - 0.12
  - 3
  - 4
  - 5
  - 6
  
install: npm install
script: make test

compiler: clang-3.6
env:
  - CXX=clang-3.6
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6
      - g++-4.8
